### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XShockinFireX** [PurePlugins/PureChat#47] opened 2016-04-20 20:10 UTC
Catchable fatal error: Object of class FactionsPro\Faction could not be converted to string in C:\Users...\plugins\PureChat-master\src_64FF00\PureChat\PureChat.php on line 468

**Comment by FaanMaario** [comment] 2016-05-25 21:25
I have the same issue; I hope this will be fixed.

Here the crashlog 

`Error: Object of class FactionsPro\Faction could not be converted to string
File: /PureChat-master/src/_64FF00/PureChat/PureChat
Line: 468
Type: E_RECOVERABLE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
æ­¤æ¬¡å‡ºé”™ç”±æ’ä»¶å¼•èµ·
BAD PLUGIN : PureChat v1.4.0

Code:
[459]             $string = str_replace("{msg}", $this->applyColors($message), $string);
[460]         }
[461]         else
[462]         {
[463]             $string = str_replace("{msg}", $this->stripColors($message), $string);
[464]         }
[465] 
[466]         if($this->factionsAPI !== null)
[467]         {
[468]             $string = str_replace("{fac_name}", $this->factionsAPI->getPlayerFaction($player), $string);
[469]             $string = str_replace("{fac_rank}", $this->factionsAPI->getPlayerRank($player), $string);
[470]         }
[471]         else
[472]         {
[473]             $string = str_replace("{fac_name}", '', $string);
[474]             $string = str_replace("{fac_rank}", '', $string);
[475]         }
[476] 
[477]         $string = str_replace("{world}", ($levelName === null ? "" : $levelName), $string);
[478] 
`

**Closed** 2017-02-27 02:52 UTC
